### ISSUE TITLE
ptrace: Operation not permitted - Attaching to local process

### ISSUE THREAD

**Issue by GM12Tick** [nsg/clion-snap#2]
Hi,

I'm using the CLION Snap for a small project.
i executed the instructions based on https://www.jetbrains.com/help/clion/attaching-to-local-process.html

I assume there is some need in the snapcraft to add plugs ? maybe process-control ?

**Comment by nsg** [comment]
This repository is the base of the snap `clion-nsg` that I never completed. There was no point of doing so when I realized that Jetbrains would make their own official snap.

I'm not sure what the correct place for help is, possible https://intellij-support.jetbrains.com/hc/en-us/?clion
